-- @ Version: SCREEN SPACE SHADERS - UPDATE 22
-- @ Description: Bloom script - Settings
-- @ Author: https://www.moddb.com/members/ascii1457
-- @ Mod: https://www.moddb.com/mods/stalker-anomaly/addons/screen-space-shaders

-- If you're not using MCM you can customize your settings here --

ssfx_default_settings = 
{
	["enabled"]			= 1.0,

	["sharpness"]		= 0.6,
	["jitter"]			= 0.5,

}

----------------------------------------------------