-- @ Version: SCREEN SPACE SHADERS - UPDATE 23
-- @ Description: Fog script - Settings
-- @ Author: https://www.moddb.com/members/ascii1457
-- @ Mod: https://www.moddb.com/mods/stalker-anomaly/addons/screen-space-shaders

-- If you're not using MCM you can customize your settings here --

ssfx_default_settings = 
{
	["height"]			= 8,
	["density"]			= 1.3,
	["suncolor"]		= 0.1,
	["scattering"]		= 0.7,
}

----------------------------------------------------